# Generated by Django 2.1.5 on 2019-04-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='LoanStatus',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Waiting for Review', 'Waiting for Review'), ('Declined', 'Declined')], default='Waiting for Review', max_length=30),
        ),
    ]
