# Generated by Django 2.1.5 on 2019-04-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_auto_20190406_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
