# Generated by Django 2.1.5 on 2019-04-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_id_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='Interest',
        ),
        migrations.AddField(
            model_name='loan',
            name='Period',
            field=models.PositiveIntegerField(default=0, help_text='In number of months'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='MonthlyPayment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='loan',
            name='TotalAmount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
