# Generated by Django 2.1.5 on 2019-04-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_auto_20190429_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='Period',
            field=models.PositiveIntegerField(default=1, help_text='In number of months'),
        ),
    ]
